### ISSUE TITLE
Error: Uncaught Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Subrosian** [edward-ly/stepmania-song-manager#1] opened 2021-04-07 15:21 UTC
In version 0.1.2, when downloading the "DanceDanceRevolution (Arcade)" pack, at a certain point it gave this error and stopped. 

![uncaught error](https://user-images.githubusercontent.com/15502619/113891083-bc978c80-9792-11eb-9ba5-f62c1624f3b1.png)

**Comment by edward-ly** [comment] 2021-04-08 06:28
My guess is, you reached the 1 hour limit for continuous downloads. Can you confirm that everything from 1st mix to X2 have already been downloaded? If so, you can try downloading the pack again and the download should resume from there.

**Comment by Subrosians** [comment] 2021-04-08 13:19
I tried it again this morning and got the same error almost immediately (maybe 10 seconds) but with a different file :

Error: Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\User\AppData\Roaming\StepMania Song Manager\Songs\ddr-arcade-simfiles\[12] DDR X2\Leaving\Leaving-jacket.png'

My downloads folder looks like below. I have confirmed that there are files in games as new as DDR A, but DDR A20 and DDR A20 Plus seem to only have single .sm files per song folder.

![image](https://user-images.githubusercontent.com/15502619/114032863-b95fd780-984a-11eb-9b87-e6bde1209a83.png)

**Comment by Subrosians** [comment] 2021-04-08 13:21
Not to double-post, but I just ran it again and got this error (different song again):

Error: Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\User\AppData\Roaming\StepMania Song Manager\Songs\ddr-arcade-simfiles\[12] DDR X2\Love Again\Love Again-jacket.png'

**Comment by edward-ly** [comment] 2021-04-08 16:29
Hmm, I think what is happening is there is something wrong with the algorithm for determining which files to download or delete when the initial download errors out, but I'll need more time to investigate and confirm. For now, though, I can close the issue if deleting the folder and starting the download over is a sufficient enough solution for you.

**Comment by Subrosians** [comment] 2021-04-08 17:22
Completely up to you, I was more testing this out for the betterment of the community. I can send you the broken songs folder for you to swap in and replicate the error (its 7GB or so RAR'd). I can also just store my broken folder for a while to test with a new build if you would like. Or, we can just call the bug closed since I did eventually have a successful download. Whichever is best for you.

**Comment by edward-ly** [comment] 2021-04-08 17:45
Sure, send me the RAR. I doubt the next version will magically fix this, but the files might be instructive.

**Comment by MircoLeo** [comment] 2021-08-09 13:36
![113891083-bc978c80-9792-11eb-9ba5-f62c1624f3b1](https://user-images.githubusercontent.com/40952901/128714832-aa944e40-27df-4635-9b9a-1aabffc515a3.png)

same download problem found in the first post

**Comment by edward-ly** [comment] 2022-01-01 05:04
Closing due to a code rewrite I did for the latest version of the app. If you guys still have any further issues, you can still re-open this issue, or start a new issue or discussion!

**Closed by edward-ly** 2022-01-01 05:04 UTC
Labels: bug
