### ISSUE TITLE
Clicking "View Song List" causes blank white window

### ISSUE THREAD

**Issue by Subrosians** [edward-ly/stepmania-song-manager#2] opened 2021-04-07 15:28 UTC
On version 0.1.2, when clicking "View Song List" on the "DanceDanceRevolution (Arcade)" pack, after about 3 seconds of the busy spinning icon on the button, a blank white window appears.

Computer is running Windows 10 20H2 (64 bit).

**Comment by edward-ly** [comment] 2021-04-08 06:39
I've been seeing the blank window recently as well, but only on Linux so far. On Windows? Either way, I'm not sure what could be the cause of this. I'll keep an eye out for this one.

**Comment by edward-ly** [comment] 2021-04-08 12:33
[https://github.com/electron-userland/electron-builder/issues/2662](https://github.com/electron-userland/electron-builder/issues/2662)

Ah, I see the problem is related to this issue. I am seeing the white screen on Windows (potentially all 3 operating systems) too, but this only occurs in the production build and not in the development build. I should be able to fix this before the next version.

**Comment by edward-ly** [comment] 2021-04-09 07:04
Now fixed in version [0.2.0](https://github.com/edward-ly/stepmania-song-manager/releases/tag/v0.2.0)

**Closed by edward-ly** 2021-04-09 07:04 UTC
Labels: bug
